### ISSUE TITLE
Blazemod: Gray mass vehicle durability value

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [Kenan2000/Bright-Nights-Kenan-Mod-Pack#23] opened 2021-03-21 09:32 UTC
Lots of them have 37000 as durability, is this intended??

**Comment by Kenan2000** [comment] 2021-03-22 03:08
@Unrepentant-Atheist Could you please explain, what exactly is the problem with blob vehicle parts having 37000 durability?Is it just the gray mass or other ones as well?If you find this value too high, can it be balanced?I definitely was not the one who assigned it there, it was there initially, it’s been done like this on purpose by the original deveoper, it seems

**Comment by Kenan2000** [comment] 2021-03-22 22:34
> I just found the jump in numbers odd from geletions, oozing to gray. It's like vanilla wood frame, metal frame and heavy duty frame, where the heavy duty frame would suddenly have 1000x the value.
> 
> It can be balanced, sure, it's just a number in .json.

Can you tell me the name of the JSON file which contains these values so I can look into it and change it possibly?

**Comment by Unrepentant-Atheist** [comment] 2021-03-23 06:06
blaze_blob_parts.json

**Comment by Kenan2000** [comment] 2021-03-23 07:30
> blaze_blob_parts.json

I'm not seeing anything wrong with it, the first type's frame durability is 250, of the second - 500 and of the third - 1000, makes sense, maybe you think that these values are too high in first place?

**Comment by Unrepentant-Atheist** [comment] 2021-03-25 07:54
```{
    "abstract" : "gray_part",
    "type" : "vehicle_part",
    "override": true,
    "copy-from" : "blob_tool",
    "name" : "metalloid part",
    "item" : "gray",
    "color" : "light_gray",
    "broken_color" : "light_gray",
    "difficulty" : 1,
    "durability" : 37000,
    "damage_modifier" : 10,
    "breaks_into" : [{
        "item" : "slime_scrap",
        "count" : [3, 8]
      }
    ],
    "damage_reduction" : {
      "all" : 10
    }```

**Comment by Kenan2000** [comment] 2021-03-25 20:03
> ```
>     "abstract" : "gray_part",
>     "type" : "vehicle_part",
>     "override": true,
>     "copy-from" : "blob_tool",
>     "name" : "metalloid part",
>     "item" : "gray",
>     "color" : "light_gray",
>     "broken_color" : "light_gray",
>     "difficulty" : 1,
>     "durability" : 37000,
>     "damage_modifier" : 10,
>     "breaks_into" : [{
>         "item" : "slime_scrap",
>         "count" : [3, 8]
>       }
>     ],
>     "damage_reduction" : {
>       "all" : 10
>     }```
> 
> 
> Durability: 37000 for example.
> ```

I've found it, the problem is not with blazemod but with M_Blazemod_Extension, it's a different small blazemod extension mod basically, I think I'm gonna delete this mod from the Modpack considering that it's neither present in my CDDA Modpack nor I'm accustomed to it and I don't possess enough information regarding it, so feel free to maintain and tweak it if you want

**Comment by Unrepentant-Atheist** [comment] 2021-03-26 06:25
Nah, don't delete it. Just tweak the values. I think something like 1500 would suffice.

**Comment by Kenan2000** [comment] 2021-03-27 14:44
Merged your PR, now I believe that the issue can be closed, thanks to your work, of course

**Closed by Kenan2000** 2021-03-27 14:44 UTC
